{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"customers\",\"employees\",\"offices\",\"order details\",\"orders\",\"payments\",\"productlines\",\"products\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_9d73ccf1-b6cd-4451-af06-a8f61d251e67",
        "fromColumn": "officeCode",
        "fromTable": "employees",
        "toColumn": "officeCode",
        "toTable": "offices"
      },
      {
        "name": "eabc5d35-92e7-49cc-aef7-85c1836980c7",
        "fromColumn": "orderDate",
        "fromTable": "orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_509199bb-1000-4d93-97ec-7bda8c6b558b"
      },
      {
        "name": "a5b0898b-495d-4356-a753-318ab37fdf2e",
        "fromColumn": "paymentDate",
        "fromTable": "payments",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a9d82bc8-cddc-4978-995c-8492ebb70e27"
      },
      {
        "name": "AutoDetected_846f5441-0d29-4f73-a73d-3ba486784ea9",
        "fromColumn": "orderNumber",
        "fromTable": "order details",
        "toColumn": "orderNumber",
        "toTable": "orders"
      },
      {
        "name": "AutoDetected_892aaedc-243f-42e1-bdcf-4f3e2ad03505",
        "fromColumn": "customerNumber",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "customerNumber",
        "toTable": "customers"
      },
      {
        "name": "AutoDetected_661ed31b-00e8-4209-a45a-beb2731fe39d",
        "fromColumn": "productCode",
        "fromTable": "order details",
        "toColumn": "productCode",
        "toTable": "products"
      },
      {
        "name": "AutoDetected_bf5e2cba-62c1-497e-ac04-e2039ae1b9a6",
        "fromColumn": "productLine",
        "fromTable": "products",
        "toColumn": "productLine",
        "toTable": "productlines"
      },
      {
        "name": "5f054f38-c353-460f-a6c0-3eb8db289b19",
        "fromColumn": "shippedDate",
        "fromTable": "orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c78a3c14-eaf0-4ee7-83de-73e2cc4a1376"
      },
      {
        "name": "816d017e-9aae-ab17-3c8f-4b12e16d334f",
        "fromColumn": "customerNumber",
        "fromTable": "payments",
        "toColumn": "customerNumber",
        "toTable": "customers"
      },
      {
        "name": "7d6c069c-d840-1321-f730-7e9c9e92df35",
        "fromColumn": "salesRepEmployeeNumber",
        "fromTable": "customers",
        "toColumn": "employeeNumber",
        "toTable": "employees"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_751eb669-2dff-4cd0-bf8d-0073f05f49e1",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2df31bc5-9509-4bd2-b9a0-99e976588d70",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1877edf8-5aeb-4cb0-9e54-1cad4ade45ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "253f6c83-cfd1-4f86-b707-1cde60926dd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0ef76020-6129-4928-a41d-5a445befabaa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ef64a58e-c738-49f1-b7a5-f61601fc58c5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e034d908-690b-4641-a38f-a5151504e6c3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e6924b89-a297-4271-82b3-c26c053c6fed",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f3ef7f81-d352-4e75-9214-9ea1a73abeff",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a6f6cc8d-934e-4eae-979c-05447ed7025b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d4b951f0-de60-45d9-8b49-27b5c2417cfb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6d77de6b-45d8-42c6-bed5-2130fd99e83b",
                "ordinal": 3
              }
            ],
            "lineageTag": "afc575d6-c439-4819-a031-7ef209710868"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4b848576-306a-4de9-ab71-f1dbeed88f9b",
        "partitions": [
          {
            "name": "DateTableTemplate_751eb669-2dff-4cd0-bf8d-0073f05f49e1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "customers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46835cfd-9193-4652-acb1-fdd0ef419f9a",
            "sourceColumn": "customerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "customerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fa780b1-cb0b-4bdd-b4da-be6c902f73b8",
            "sourceColumn": "customerName",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "528bc399-e264-4472-9f1a-576aa9d3aa27",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56e79663-bc7b-48f3-a00e-bc758440225d",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "salesRepEmployeeNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e095c33-26b9-4de6-869f-f15bc2bc51c4",
            "sourceColumn": "salesRepEmployeeNumber",
            "summarizeBy": "none"
          },
          {
            "name": "creditLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "138ff58a-cbac-4dea-9275-d58403224e46",
            "sourceColumn": "creditLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "FullName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b69c463-5172-4d30-bb8f-aa4f155ddbea",
            "sourceColumn": "FullName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1395d7a6-fabd-423f-a627-2e27d64fc06e",
        "measures": [
          {
            "name": "total_sales",
            "lineageTag": "34cafa8c-a6f8-49fd-a747-512852c7d4d7"
          }
        ],
        "partitions": [
          {
            "name": "customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_customers csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"customers.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_customers csv1\",[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customerNumber\", Int64.Type}, {\"customerName\", type text}, {\"contactLastName\", type text}, {\"contactFirstName\", type text}, {\"phone\", type text}, {\"addressLine1\", type text}, {\"addressLine2\", type text}, {\"city\", type text}, {\"state\", type text}, {\"postalCode\", type text}, {\"country\", type text}, {\"salesRepEmployeeNumber\", type text}, {\"creditLimit\", Int64.Type}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type\",{{\"contactFirstName\", Text.Trim, type text}, {\"contactLastName\", Text.Trim, type text}}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Trimmed Text\",{\"contactLastName\", \"contactFirstName\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"FullName\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Merged Columns\",\"NULL\",null,Replacer.ReplaceValue,{\"state\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"state\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Removed Columns\",\"NULL\",null,Replacer.ReplaceValue,{\"salesRepEmployeeNumber\"}),",
                "    #\"Filled Down\" = Table.FillDown(#\"Replaced Value1\",{\"salesRepEmployeeNumber\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filled Down\",{\"phone\", \"addressLine1\", \"addressLine2\", \"postalCode\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"creditLimit\", Currency.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "employees",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "employeeNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc76d6d5-c1c7-42fa-9ea2-a537bb5c7c92",
            "sourceColumn": "employeeNumber",
            "summarizeBy": "none"
          },
          {
            "name": "lastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72fd7357-9a8d-4b24-825a-aa05158ce39a",
            "sourceColumn": "lastName",
            "summarizeBy": "none"
          },
          {
            "name": "firstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5195d9c1-e03a-4ee5-b190-4d933e9e583d",
            "sourceColumn": "firstName",
            "summarizeBy": "none"
          },
          {
            "name": "extension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "883fdc5f-7a3b-4c04-a1f1-b15ffa269073",
            "sourceColumn": "extension",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08bfb85a-79eb-4f6c-89a6-c3aababd432e",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "officeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64df23ae-c50a-452d-a4cf-c5a74791d20a",
            "sourceColumn": "officeCode",
            "summarizeBy": "none"
          },
          {
            "name": "reportsTo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75e85e92-d8ea-4537-b3de-f36413eb09b6",
            "sourceColumn": "reportsTo",
            "summarizeBy": "none"
          },
          {
            "name": "jobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0dab340-bd81-4718-9584-f88dc037bc82",
            "sourceColumn": "jobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "usernames",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6982b5e0-d40f-4a31-b1f8-5a6fd6a14158",
            "sourceColumn": "usernames",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2186d47-79d4-464a-bd53-cee327fab99f",
        "partitions": [
          {
            "name": "employees",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_employees csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"employees.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_employees csv1\",[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"employeeNumber\", Int64.Type}, {\"lastName\", type text}, {\"firstName\", type text}, {\"extension\", type text}, {\"email\", type text}, {\"officeCode\", Int64.Type}, {\"reportsTo\", type text}, {\"jobTitle\", type text}}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Changed Type\", \"Text Before Delimiter\", each Text.BeforeDelimiter([email], \"@\"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"Text Before Delimiter\", \"usernames\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "offices",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "officeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ede83469-7269-4ba9-8cd2-c737e6ade46e",
            "sourceColumn": "officeCode",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11fced6e-d5a6-4ba8-bd19-0090ff4c368c",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cb8e792-2275-46a9-a4a9-5e46f72c9357",
            "sourceColumn": "phone",
            "summarizeBy": "none"
          },
          {
            "name": "addressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9e7e8ab-39c0-4483-bb85-818382673eb7",
            "sourceColumn": "addressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a20d0227-ad54-4a5a-80fb-bf76b991b345",
            "sourceColumn": "state",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e0199c0-9f7a-4954-a285-492b4d74d7e9",
            "sourceColumn": "country",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0ddac211-8aa1-4c41-a337-d38f211bc750",
        "partitions": [
          {
            "name": "offices",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_offices csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"offices.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_offices csv1\",[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"officeCode\", Int64.Type}, {\"city\", type text}, {\"phone\", type text}, {\"addressLine1\", type text}, {\"addressLine2\", type text}, {\"state\", type text}, {\"country\", type text}, {\"postalCode\", type text}, {\"territory\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"addressLine2\", \"postalCode\", \"territory\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"NULL\",null,Replacer.ReplaceValue,{\"state\"}),",
                "    #\"Filled Down\" = Table.FillDown(#\"Replaced Value\",{\"state\"})",
                "in",
                "    #\"Filled Down\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "order details",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "orderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ba2e267-bd90-4aed-b531-9504cd947b82",
            "sourceColumn": "orderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "productCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23b551b2-1365-42b4-8457-1ae210cac552",
            "sourceColumn": "productCode",
            "summarizeBy": "none"
          },
          {
            "name": "quantityOrdered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c45b78cf-4abe-4e1f-8dae-074c9f01c50e",
            "sourceColumn": "quantityOrdered",
            "summarizeBy": "sum"
          },
          {
            "name": "priceEach",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02555fb3-fda2-4c8d-881e-365fd013668a",
            "sourceColumn": "priceEach",
            "summarizeBy": "sum"
          },
          {
            "name": "orderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92e92c35-1263-484c-b2d5-2b844217f257",
            "sourceColumn": "orderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3c6121da-f3a8-4a80-bd36-8cbe50a86ed3",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "buyPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cf0152c3-31a4-440c-a976-6d627b760d37",
            "sourceColumn": "buyPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "total_buy_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6da8fdf1-93f2-47e4-81a7-ee919271bd89",
            "sourceColumn": "total_buy_price",
            "summarizeBy": "sum"
          },
          {
            "name": "profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7d4085e8-684d-47ce-8193-d0e5802787c5",
            "sourceColumn": "profit",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f9006fae-bc37-4d4f-9b2f-c052887168e6",
        "measures": [
          {
            "name": "total_profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "sum('order details'[profit])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2772e366-858b-4d58-b4f9-e87e1b2c0db2"
          }
        ],
        "partitions": [
          {
            "name": "order details",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_order details csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"order details.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_order details csv1\",[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderNumber\", Int64.Type}, {\"productCode\", type text}, {\"quantityOrdered\", Int64.Type}, {\"priceEach\", type number}, {\"orderLineNumber\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sales\", each [quantityOrdered]*[priceEach]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Sales\", Currency.Type}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type1\", {\"productCode\"}, products, {\"productCode\"}, \"products\", JoinKind.Inner),",
                "    #\"Expanded products\" = Table.ExpandTableColumn(#\"Merged Queries\", \"products\", {\"buyPrice\"}, {\"buyPrice\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Expanded products\", \"Margin\", each [buyPrice]*[quantityOrdered]),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"profit\", each [Sales]-[Margin]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom2\",{{\"Margin\", \"total_buy_price\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"orderNumber\", \"productCode\", \"quantityOrdered\", \"priceEach\", \"orderLineNumber\", \"buyPrice\", \"Sales\", \"total_buy_price\", \"profit\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"total_buy_price\", Currency.Type}, {\"profit\", Currency.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "orderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10a6f75c-fe69-47a2-b8be-c4f8ab5e4e18",
            "sourceColumn": "orderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "orderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3a6bf4e1-0ded-4fd8-a5e5-637db5795c05",
            "sourceColumn": "orderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_509199bb-1000-4d93-97ec-7bda8c6b558b"
                },
                "isDefault": true,
                "relationship": "eabc5d35-92e7-49cc-aef7-85c1836980c7"
              }
            ]
          },
          {
            "name": "requiredDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1cff6b0-c376-4e49-99a0-2515b319d139",
            "sourceColumn": "requiredDate",
            "summarizeBy": "none"
          },
          {
            "name": "shippedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c4dcdf7a-d860-42b3-a871-11ea8c28b402",
            "sourceColumn": "shippedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c78a3c14-eaf0-4ee7-83de-73e2cc4a1376"
                },
                "isDefault": true,
                "relationship": "5f054f38-c353-460f-a6c0-3eb8db289b19"
              }
            ]
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77a21ab6-3421-4c76-9903-151c170973b2",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "customerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f15ac371-bcfa-464b-a10b-a51d767c7a56",
            "sourceColumn": "customerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3af724b8-90ac-4eb4-a64d-2de25442d51a",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "56865b8d-14d3-4c59-ab6e-ab59b9c66787",
            "sourceColumn": "Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61a455d9-344f-4202-8ac9-9494831d382b",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3f42a750-ac67-45c0-b87c-53713ec0c290",
        "partitions": [
          {
            "name": "orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_orders csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"orders.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_orders csv1\",[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"comments\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"NULL\",null,Replacer.ReplaceValue,{\"shippedDate\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"shippedDate\", type date}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"orderDate\", type date}}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Changed Type1\", \"Month Name\", each Date.MonthName([orderDate]), type text),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Inserted Month Name\", \"Shipping_days\", each [shippedDate]-[orderDate]),",
                "    #\"Inserted Days\" = Table.AddColumn(#\"Added Custom\", \"Days\", each Duration.Days([Shipping_days]), Int64.Type),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Inserted Days\",{\"Shipping_days\"}),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Removed Columns1\", \"Day Name\", each Date.DayOfWeekName([orderDate]), type text)",
                "in",
                "    #\"Inserted Day Name\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_509199bb-1000-4d93-97ec-7bda8c6b558b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "790f4c7f-ef91-4d85-b71b-cb641f7eb04a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "34d1bc50-e1e9-4f25-a61b-03f3f8508ca7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17352551-afed-439e-9ace-9c1ef64c37eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "72f0d9e3-bc17-4b9b-aeca-008efdb81f94",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cabc5b87-d445-4224-9f8e-f66faf64da0a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ad096141-4e17-43e4-83c5-a772ab4298a0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c7a593d-4132-45ef-bc93-62312f569074",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1780e2c8-ce76-4f73-b5b8-67ed08cde4de",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "14bad27e-5c41-4ee1-a68e-01b217b3ee63",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "80478728-5b00-4289-81b1-59fda68a9fb1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7f0f046e-a8f8-4ce1-b20f-4e5b526f20d5",
                "ordinal": 3
              }
            ],
            "lineageTag": "db0de0ba-323e-4dca-9187-dae6c1e81569"
          }
        ],
        "isHidden": true,
        "lineageTag": "0cd7c404-9b46-43e6-a3b8-cf2f625765ab",
        "partitions": [
          {
            "name": "LocalDateTable_509199bb-1000-4d93-97ec-7bda8c6b558b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders'[orderDate])), 1, 1), Date(Year(MAX('orders'[orderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "payments",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec9469a3-4340-4e18-9d98-5903dff908d2",
            "sourceColumn": "customerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "checkNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73bd7e46-5e44-4e53-bc90-8901a7bdccf4",
            "sourceColumn": "checkNumber",
            "summarizeBy": "none"
          },
          {
            "name": "paymentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1f51bd81-d69c-4640-813a-d584fa3a9a81",
            "sourceColumn": "paymentDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a9d82bc8-cddc-4978-995c-8492ebb70e27"
                },
                "isDefault": true,
                "relationship": "a5b0898b-495d-4356-a753-318ab37fdf2e"
              }
            ]
          },
          {
            "name": "amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "b7b54a27-f64c-4ba8-9249-0f1fb71beb9f",
            "sourceColumn": "amount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d1c8003c-93b3-4885-9dc6-7160d1ed6fca",
        "partitions": [
          {
            "name": "payments",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_payments csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"payments.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_payments csv1\",[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customerNumber\", Int64.Type}, {\"checkNumber\", type text}, {\"paymentDate\", type date}, {\"amount\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a9d82bc8-cddc-4978-995c-8492ebb70e27",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2d707ede-f0f4-4c82-9315-40f7623127af",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6dccae6-383a-4eaf-83e4-d5474495dcdb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cc85ba4d-b508-4f04-8688-c82002ab926e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1c5c7c32-4867-4d8d-a735-4d1eab42fe3b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1a76a7b5-15b8-497c-a6f9-957c43c1b3e2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "410778c4-97a3-439b-bd21-a2d6f9657f2b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "73a5701b-3818-4687-954e-9087400fae9b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "708ef01d-9431-479a-bbd3-7cd4ec4f4075",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "058f8cdb-5bca-47eb-8cb8-f3c01c05aed0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bdb9e3c8-1e3c-4076-977e-364d72cf822b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c0c20da9-91fb-4867-bc20-66183f2ef793",
                "ordinal": 3
              }
            ],
            "lineageTag": "f2b566ff-04be-46e9-857e-33f0f6f470fb"
          }
        ],
        "isHidden": true,
        "lineageTag": "10738525-c298-43dc-9cd8-eb3f277ab06e",
        "partitions": [
          {
            "name": "LocalDateTable_a9d82bc8-cddc-4978-995c-8492ebb70e27",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('payments'[paymentDate])), 1, 1), Date(Year(MAX('payments'[paymentDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "productlines",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "productLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b97bb00-75ff-4d6e-9b58-f8ebc46436ff",
            "sourceColumn": "productLine",
            "summarizeBy": "none"
          },
          {
            "name": "textDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "672d0595-d5a2-4737-958e-ade8a7628b57",
            "sourceColumn": "textDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a2887a79-92d5-4735-87f2-420361bf0a00",
        "partitions": [
          {
            "name": "productlines",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_productlines csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"productlines.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_productlines csv1\",[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Imported CSV\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"productLine\", type text}, {\"textDescription\", type text}, {\"htmlDescription\", type text}, {\"image\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"htmlDescription\", \"image\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "productCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33914a70-33ae-4ab0-9f03-7cce84340369",
            "sourceColumn": "productCode",
            "summarizeBy": "none"
          },
          {
            "name": "productName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e51acf38-4a96-48fc-9f33-01cf8e749240",
            "sourceColumn": "productName",
            "summarizeBy": "none"
          },
          {
            "name": "productLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d2f8c97-3f8b-4b17-9152-bb6ed3d90479",
            "sourceColumn": "productLine",
            "summarizeBy": "none"
          },
          {
            "name": "productVendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f8821ab-7a21-4742-b436-181d976a36ec",
            "sourceColumn": "productVendor",
            "summarizeBy": "none"
          },
          {
            "name": "productDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e51f4e40-963e-45f1-8551-116b14429703",
            "sourceColumn": "productDescription",
            "summarizeBy": "none"
          },
          {
            "name": "quantityInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f6afc32-f3b9-4646-8514-80339d4839dd",
            "sourceColumn": "quantityInStock",
            "summarizeBy": "sum"
          },
          {
            "name": "buyPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2fc9952-7fbc-4770-b877-133115da5675",
            "sourceColumn": "buyPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "MSRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "670d6847-771e-4a22-b3cd-27831c42cb69",
            "sourceColumn": "MSRP",
            "summarizeBy": "sum"
          },
          {
            "name": "Custom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efc87972-c983-4910-b3dd-0b6e19657bda",
            "sourceColumn": "Custom",
            "summarizeBy": "none"
          },
          {
            "name": "stock_requirment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(products[quantityInStock]>500 , \"No\", \"Yes\")",
            "isDataTypeInferred": true,
            "lineageTag": "4083be43-dc7e-4ddf-b9ed-4385de2857b1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "fc2e9f70-13d4-49b2-8e15-7dfb51611238",
        "partitions": [
          {
            "name": "products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\"),",
                "    #\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_products csv1\" = Source{[#\"Folder Path\"=\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\\",Name=\"products.csv\"]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\Administrator\\OneDrive\\Desktop\\PB\\classicmodels\\_products csv1\",[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"productCode\", type text}, {\"productName\", type text}, {\"productLine\", type text}, {\"productVendor\", type text}, {\"productDescription\", type text}, {\"quantityInStock\", Int64.Type}, {\"buyPrice\", type number}, {\"MSRP\", type number}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [quantityInStock] >= 1000 then \"not required\" else \"required\")",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c78a3c14-eaf0-4ee7-83de-73e2cc4a1376",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "889e0801-a3cd-4549-89f7-9eb083c31003",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d7fdee07-ed2c-46e1-b36d-bd8355f343dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7499279f-816d-4805-ac7d-b96aa20cabd2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6288e2e4-8602-490b-b213-80eb9d5d167f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "855e6658-afa2-47ee-be06-041a1718f666",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "82a3b0b0-b6fc-4d44-bcca-2e87dafd77aa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "178cab77-0bd3-4f02-b332-85504ea4d785",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "65a97a31-db73-493a-93cd-b8f6dfe5b521",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9a35018b-63a7-4044-9ab1-8054dcf97c48",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c6ed0d2c-12b1-4694-a01b-96248086911a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f81cc7d2-7693-4040-adb5-ed922ed85481",
                "ordinal": 3
              }
            ],
            "lineageTag": "3f369ff6-11fb-46ec-b17c-7b7410d499ba"
          }
        ],
        "isHidden": true,
        "lineageTag": "2976a7b5-9970-4d78-a1c5-e94e5b1f63fd",
        "partitions": [
          {
            "name": "LocalDateTable_c78a3c14-eaf0-4ee7-83de-73e2cc4a1376",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders'[shippedDate])), 1, 1), Date(Year(MAX('orders'[shippedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}